name: App CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '*.md'

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: INSTALL
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
          run_install: true

      - name: BUILD
        run: pnpm build:ci

      - name: TEST
        run: pnpm test:ci

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/lcov.info

  coverage:
    name: Coverage analysis
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: CODECOV
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
